Fix: Sadaf-Validation-updates
Fleet-Hawks-Inc/fh-cloud-app pull request #1164
Opened 2021-05-20 15:20 UTC by sadaf510

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-05-20 18:44 UTC, Hardeep8587 reviewed
please address all the comments plus check required conditons and error messages, thanku

2021-05-20 18:44 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                          <ng-select [multiple]="true" [(ngModel)]="coDrivers" name="coDrivers" placeholder="Select Co-Driver" #Acodriver="ngModel" required>
@sadaf510 Co driver is optional

2021-05-20 18:44 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              [(ngModel)]="shipment.goodsAstrayDateOfExit" #goodast="ngModel" required>
this is required when shipement type is GOODS_ASTRAY, plz refer to onboarrd biz country validattion

2021-05-20 18:44 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                  [ngModelOptions]="{standalone: true}" [(ngModel)]="shipment.inBondDetails.type" #inbond="ngModel" required>
plz check condition when it is required

2021-05-20 18:44 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              <div *ngIf="thirdName.invalid && (thirdName.dirty || thirdName.touched)" class="text-danger">
please check conditions. from PDF

2021-05-20 20:09 UTC, sadaf510 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                  [ngModelOptions]="{standalone: true}" [(ngModel)]="shipment.inBondDetails.type" #inbond="ngModel" required>
yes it is according to the pdf

2021-05-20 20:11 UTC, sadaf510 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              <div *ngIf="thirdName.invalid && (thirdName.dirty || thirdName.touched)" class="text-danger">
pdf doesn't contain any particular pattern for this field.

2021-05-20 20:12 UTC, sadaf510 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              [(ngModel)]="shipment.goodsAstrayDateOfExit" #goodast="ngModel" required>
It is according to pdf. Still, I'll check.

2021-05-21 05:00 UTC, kunalfleethawks requested changes
Please address review comments

2021-05-21 05:00 UTC, kunalfleethawks commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.ts
> +    console.log('this.shippers ',this.shippers );
Remove console logs

2021-05-21 11:07 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                  [ngModelOptions]="{standalone: true}" [(ngModel)]="shipment.inBondDetails.type" #inbond="ngModel" required>
bind required field, refer to DOT required field in onboard

2021-05-21 11:07 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              <div *ngIf="thirdName.invalid && (thirdName.dirty || thirdName.touched)" class="text-danger">
can't make all required, this is wt I meant

2021-05-22 08:36 UTC, sadaf510 commented
> please address all the comments plus check required conditons and error messages, thanku

All the changes have been done , the functionality such as add, update and delete are working fine. Save buttons are disabled . Please check , still any changes required let me know.

2021-05-22 08:55 UTC, sadaf510 commented
@Hardeep8587 please check ACI validations. All changes are done according to ACE.
https://github.com/Fleet-Hawks-Inc/fh-cloud-app/pull/1164/commits/960d6da8c40e99ff9ddce74200a6f32f7bb40482

2021-05-24 10:47 UTC, Hardeep8587 reviewed
@sadaf510 Please check patterns, conditions and the messages ( capital/small caase)

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/fleet/inventory/add-inventory/add-inventory.component.html
> +                            #iAisle="ngModel" pattern="^[0-9]$"
@sadaf510 Please check pattern

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/fleet/inventory/add-inventory/add-inventory.component.html
> +                            #iRow="ngModel" pattern="^[0-9]$"
same pattern

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/fleet/inventory/add-inventory/add-inventory.component.html
> +                            #iBin="ngModel" pattern="^[0-9]$"
Same pattern

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/fleet/maintenance/service-program/add-service-program/add-service-program.component.html
> +                                                  [attr.name]="'serviceScheduleDetails['+i+'].repeatByTime'" [ngModelOptions]="{standalone: true}" type="text" class="form-control" #Rtime="ngModel" re
please check pattern

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              Trip Number must contain alpha-numeric with no spaces or special characters, letters must be upper case.
@sadaf510 Specify the length of the trip number

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              [(ngModel)]='seal.sealNumber'#Aseal="ngModel" pattern="^[a-zA-Z0-9]{4}$">
@sadaf510 Please cehck pattern, it will allow only 4 characters

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                Document# must contain Alphanumeric, dashes ,spaces and no other characters.
please take care when to user block letters when mall, alphanumeric  not Alphanumeric

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                               placeholder="Type Address" [disabled]="usAddress.address.manual"  [class.error]="errorClassUserLocation" #USadd="ngModel" required>
bind required

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              [ngModelOptions]="{standalone: true}" #ShipT="ngModel" [required]="shipments.length === 0">
!== 0

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                              placeholder="Select asset" [(ngModel)]="commodity.loadedOn.number" #AssetNum1="ngModel" [required]="shipments.length === 0">
required when shipment length is > 0

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                    Commodity Value in USD must contain Numeric, with one decimal allowed. System will round to nearest whole number, or up to 1 if less than 1 before
Please read, don't copy paste

2021-05-24 10:47 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.html
> +                                      [(ngModel)]='seal.sealNumber' #A2seal="ngModel" pattern="^[a-zA-Z0-9]{4}$">
check pattern

2021-05-24 16:25 UTC, Hardeep8587 approved these changes
Approved

2021-05-24 16:25 UTC, Hardeep8587 commented
@kunalfleethawks please review an merge! thanku

2021-05-25 08:24 UTC, merged