fix: statewise miles calculation in trips
Fleet-Hawks-Inc/fh-cloud-app pull request #1330
Opened 2021-06-12 10:28 UTC by FH-sandeepkaur1

## Change Description

statewise miles calculation in trips
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-12 10:54 UTC, kunalfleethawks requested changes

2021-06-12 10:54 UTC, kunalfleethawks commented on src/app/services/google-maps.service.ts
> +  stateWisePCMilesDistance(stops) {
Write a service api in back end and call this api from cloud service as we are exposing api key of pcmiler which can be used by attacker

2021-06-12 10:55 UTC, FH-sandeepkaur1 commented on src/app/services/google-maps.service.ts
> +  stateWisePCMilesDistance(stops) {
okay doing it.

2021-06-14 12:29 UTC, kunalfleethawks approved these changes

2021-06-14 12:29 UTC, merged