feat: e2e test cases of whole address book and inspection form
Fleet-Hawks-Inc/fh-cloud-app pull request #1476
Opened 2021-07-20 11:40 UTC by rashmi0301

## Change Description

Done e2e test cases of address book and inspection form
Created the test cases for user tab as well

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-20 11:41 UTC, rashmi0301 commented
@kunalfleethawks please review it .
Thanks

2021-07-21 05:02 UTC, kunalfleethawks requested changes
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:02 UTC, kunalfleethawks commented on cypress/integration/address_customer.js
> +    cy.get('#btnsubmit').click();
Take this url from cypress environment variable. Please refer to driver test cases

2021-07-21 05:26 UTC, rashmi0301 commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
okay . I'll do it for all

2021-07-21 07:37 UTC, rashmi0301 commented on cypress/integration/address_customer.js
> +    cy.get('#btnsubmit').click();
Done

2021-07-21 07:38 UTC, rashmi0301 commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
DONE

2021-07-21 07:38 UTC, rashmi0301 commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
DONE

2021-07-21 07:38 UTC, rashmi0301 commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
DONE

2021-07-21 07:38 UTC, rashmi0301 commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
DONE

2021-07-21 07:38 UTC, rashmi0301 commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
DONE

2021-07-21 07:43 UTC, rashmi0301 commented
@kunalfleethawks please review it  above changes and new test cases for user . 
Thanks

2021-07-21 09:21 UTC, rashmi0301 commented on cypress/integration/address_broker.js
> +    cy.visit('http://localhost:4200/#');
DONE

2021-07-21 09:21 UTC, rashmi0301 commented on cypress/integration/address_customer.js
> +    cy.visit('http://localhost:4200/');
DONE

2021-07-21 11:07 UTC, kunalfleethawks approved these changes

2021-07-21 11:07 UTC, merged