fixed: Final vehicle summary Report
Fleet-Hawks-Inc/fh-cloud-app pull request #1935
Opened 2021-11-06 12:23 UTC by saurkarankita

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-09 04:57 UTC, FH-sandeepkaur1 commented on src/app/pages/reports/fleet/vehicle-report/summary/summary.component.html
> +                            <ng-option value="outOfService">OutOfService</ng-option>
Please add spacing in OutOfService text. 
![image](https://user-images.githubusercontent.com/72725109/140865012-097c7231-a775-4174-bfda-3e7a04bae291.png)

2021-11-09 04:57 UTC, FH-sandeepkaur1 requested changes
Please review changes

2021-11-09 05:38 UTC, FH-sandeepkaur1 approved these changes

2021-11-10 03:20 UTC, FH-sandeepkaur1 requested changes

2021-11-10 03:20 UTC, FH-sandeepkaur1 commented on src/app/pages/reports/fleet/fuel-report/summary/summary.component.html
> +                                    <span class="input-group-text">
Please remove commented code

2021-11-10 03:39 UTC, saurkarankita commented on src/app/pages/reports/fleet/fuel-report/summary/summary.component.html
> +                                    <span class="input-group-text">
Okay Sandeep

2021-11-12 04:50 UTC, merged