add: changes in fuel summary report
Fleet-Hawks-Inc/fh-cloud-app pull request #2019
Opened 2021-11-24 05:35 UTC by saurkarankita

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-24 11:19 UTC, FH-sandeepkaur1 requested changes

2021-11-24 11:19 UTC, FH-sandeepkaur1 commented on src/app/pages/reports/fleet/fuel-report/summary/summary.component.html
> +                                    <p class="tileCur mt-0 mb-0">{{fuelCount.l_quantity}} Litres</p>
Please use LTR instead of litres and GL for gallons in fuel reports.
Change Litres/gallons to unit in table heading

2021-11-26 07:23 UTC, saurkarankita commented on src/app/pages/reports/fleet/fuel-report/summary/summary.component.html
> +                                    <p class="tileCur mt-0 mb-0">{{fuelCount.l_quantity}} Litres</p>
done

2021-11-26 08:03 UTC, FH-sandeepkaur1 approved these changes

2021-11-26 09:01 UTC, kunalfleethawks approved these changes

2021-11-26 09:01 UTC, merged