feat: driver-activity-report
Fleet-Hawks-Inc/fh-cloud-app pull request #2024
Opened 2021-11-24 13:20 UTC by Harmanfleet

feat: driver-activity-report

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-25 16:37 UTC, kunalfleethawks requested changes
Please address review comments

2021-11-25 16:37 UTC, kunalfleethawks commented on src/app/pages/reports/fleet/drivers/driver-data/driver-data.component.ts
> +  fetchDriversCount() {
Merge it into single api

2021-11-25 16:37 UTC, kunalfleethawks commented on src/app/pages/reports/fleet/drivers/driver-data/driver-data.component.ts
> +      .getData(
Please implement infinite paging

2021-11-25 16:37 UTC, kunalfleethawks commented on src/app/pages/reports/fleet/drivers/driver-data/driver-data.component.ts
> +      this.vehiclesObject = result;
Merge into single api

2021-12-02 04:49 UTC, FH-sandeepkaur1 approved these changes

2021-12-02 05:22 UTC, kunalfleethawks approved these changes

2021-12-02 05:24 UTC, merged