fix: csv report and infinite pagination
Fleet-Hawks-Inc/fh-cloud-app pull request #2051
Opened 2021-11-30 13:38 UTC by jaspret1

## Change Description
now I had done infinite pagination when we search data in the asset activity report
and I also fixed csv now we get all data when we export CSV in asset and service log
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-01 04:28 UTC, FH-sandeepkaur1 requested changes

2021-12-01 04:28 UTC, FH-sandeepkaur1 commented on src/app/pages/reports/fleet/asset-report/activity-list/activity-list.component.html
> +                            <span class="driverstatus"><i class="fas fa-map-marker-alt"></i> Crescent Road Vancouver, BC
Please remove unwanted code.

2021-12-01 15:41 UTC, kunalfleethawks approved these changes

2021-12-01 15:41 UTC, merged

2021-12-02 04:51 UTC, jaspret1 commented on src/app/pages/reports/fleet/asset-report/activity-list/activity-list.component.html
> +                            <span class="driverstatus"><i class="fas fa-map-marker-alt"></i> Crescent Road Vancouver, BC
it was done