feat : updated rented/leased in assets module
Fleet-Hawks-Inc/fh-cloud-app pull request #2056
Opened 2021-12-01 12:01 UTC by saurkarankita

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-02 04:56 UTC, FH-sandeepkaur1 requested changes

2021-12-02 04:56 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/assets/add-assets/add-assets.component.ts
> +            result.assetDetails.ownDate;
Please refractor this code

2021-12-02 04:56 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/assets/add-assets/add-assets.component.ts
> +
Please remove extra spaces

2021-12-02 04:56 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/assets/asset-detail/asset-detail.component.html
> +                                                        <td class="text-capitalize">
Please refractor this code. You can combine both the conditions by using an OR operator for leased and rented.

2021-12-02 05:01 UTC, saurkarankita commented on src/app/pages/fleet/assets/add-assets/add-assets.component.ts
> +
ok

2021-12-06 02:58 UTC, saurkarankita commented
Conflicts and conversation resolved in new PR here is 
https://github.com/Fleet-Hawks-Inc/fh-cloud-app/pull/2089
review and merge

2021-12-06 04:33 UTC, closed without merging

2021-12-06 04:47 UTC, saurkarankita commented
issues solved in another PR.