feat: company-profile
Fleet-Hawks-Inc/fh-cloud-app pull request #2078
Opened 2021-12-03 12:41 UTC by Harmanfleet

add terms and conditions field

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-04 03:56 UTC, kunalfleethawks requested changes
@Harmanfleet please comment on the question

2021-12-04 03:56 UTC, kunalfleethawks commented on src/app/pages/fleet/fuel/fuel-entry-list/fuel-entry-list.component.ts
> +            element.dateTime = moment(element.transactionDateTime).format('MMM Do YYYY, h:mm a')
What does the `Do` signify in `MMM Do YYYY, h:mm a`

2021-12-04 03:57 UTC, kunalfleethawks commented
please resolve the conflict

2021-12-04 03:58 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/fuel/fuel-entry-list/fuel-entry-list.component.html
> -                      <ng-template ngx-datatable-cell-template let-rowIndex="rowIndex" let-value="value"
Please rectify this code

2021-12-06 04:16 UTC, FH-sandeepkaur1 requested changes

2021-12-06 04:16 UTC, FH-sandeepkaur1 commented on src/app/pages/manage/company/company-profile/company-profile.component.html
> +                        <td class="back-color-gray">Dispatch Notes For Driver</td>
Please check your binding variables

2021-12-06 05:07 UTC, FH-sandeepkaur1 approved these changes

2021-12-06 05:28 UTC, kunalfleethawks approved these changes

2021-12-06 05:28 UTC, merged