feat: schema change of service program
Fleet-Hawks-Inc/fh-cloud-app pull request #2147
Opened 2021-12-15 12:03 UTC by jaspret1

## Change Description
 I have changed the schema of the service program with one table and I changed get, add, put, delete, getById, getList, pagination, and searching API 
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-18 05:01 UTC, FH-sandeepkaur1 requested changes

2021-12-18 05:01 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/maintenance/service-program/service-program-list/service-program-list.component.ts
> +  //   this.suggestions = [];
why this function is commented?

2021-12-18 05:01 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/maintenance/service-program/add-service-program/add-service-program.component.ts
> +  programID = [];
this is not required

2022-01-07 09:48 UTC, jaspret1 commented on src/app/pages/fleet/maintenance/service-program/service-program-list/service-program-list.component.ts
> +  //   this.suggestions = [];
now I have uncommented this code

2022-01-07 09:51 UTC, jaspret1 commented on src/app/pages/fleet/maintenance/service-program/add-service-program/add-service-program.component.ts
> +  programID = [];
i have removed that code

2022-01-10 05:32 UTC, FH-sandeepkaur1 approved these changes

2022-01-10 08:44 UTC, merged