fix: pdf for collection reports
Fleet-Hawks-Inc/fh-cloud-app pull request #2227
Opened 2021-12-27 17:01 UTC by AmitojSingh1

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-12-28 03:42 UTC, kunalfleethawks approved these changes

2021-12-28 03:42 UTC, kunalfleethawks requested changes
Please respond to review comment

2021-12-28 03:42 UTC, kunalfleethawks commented on src/app/pages/reports/accounts/customer-collection/customer-collection.component.ts
> +      margin: 0,
Why did you revert the code ?

2021-12-28 16:07 UTC, AmitojSingh1 commented on src/app/pages/reports/accounts/customer-collection/customer-collection.component.ts
> +      margin: 0,
this page break is not working as expected. and adding margin and shrinking the table to the right. so I have to remove it from here. but for longer and combined reports it's working fine. so m using there.

2021-12-29 03:48 UTC, kunalfleethawks commented on src/app/pages/reports/accounts/customer-collection/customer-collection.component.ts
> +      margin: 0,
Ok. I hope it does not chop off the text in the long run and we have to do it again.

2021-12-29 03:48 UTC, merged