feat: aws s3 issue fixed while editing attachments in fleet module
Fleet-Hawks-Inc/fh-cloud-app pull request #2299
Opened 2022-01-07 09:12 UTC by PratikGanjareFleetHawks

fleet module

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-10 06:29 UTC, FH-sandeepkaur1 requested changes

2022-01-10 06:29 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/drivers/add-driver/add-driver.component.html
> +        <div class="row"*ngFor="let item of driverProfileSrc;">
Why for loop is added here. Single image is uploaded in driver profile

2022-01-10 07:30 UTC, PratikGanjareFleetHawks commented on src/app/pages/fleet/drivers/add-driver/add-driver.component.html
> +        <div class="row"*ngFor="let item of driverProfileSrc;">
ok . Let me check .I will Re-commit it.

2022-01-10 14:02 UTC, PratikGanjareFleetHawks commented on src/app/pages/fleet/drivers/add-driver/add-driver.component.html
> +        <div class="row"*ngFor="let item of driverProfileSrc;">
Resolved

2022-01-12 04:58 UTC, FH-sandeepkaur1 approved these changes

2022-01-12 05:12 UTC, merged