feat: fixed aws url issues while opening documents in new tab
Fleet-Hawks-Inc/fh-cloud-app pull request #2325
Opened 2022-01-14 07:49 UTC by PratikGanjareFleetHawks

## Change Description

I am added changes in driver,vehicles,assets
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-14 12:46 UTC, FH-sandeepkaur1 requested changes

2022-01-14 12:46 UTC, FH-sandeepkaur1 commented on src/app/pages/fleet/assets/asset-detail/asset-detail.component.html
> +                                                    <a href="{{ data.path }}">Document {{ i+1}}</a>
Why `<td width="80%">` is removed?

2022-01-14 17:11 UTC, PratikGanjareFleetHawks commented on src/app/pages/fleet/assets/asset-detail/asset-detail.component.html
> +                                                    <a href="{{ data.path }}">Document {{ i+1}}</a>
Solved.  @FH-sandeepkaur1

2022-01-15 06:43 UTC, FH-sandeepkaur1 approved these changes

2022-01-15 06:44 UTC, merged