feat: import feature in vehicles
Fleet-Hawks-Inc/fh-cloud-app pull request #2352
Opened 2022-01-21 06:30 UTC by PratikGanjareFleetHawks

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-24 04:21 UTC, kunalfleethawks commented on src/app/pages/manage/settings/veh-import/veh-import.component.ts
> +          this.toastr.error("Don't upload empty CSV.")
There are no records in the file uploaded.

2022-01-24 04:21 UTC, kunalfleethawks commented on src/app/pages/manage/settings/veh-import/veh-import.component.ts
> +         this.toastr.error("'Recored should be less than 200'")}
The file should contain a maximum of 200 records.

2022-01-24 04:21 UTC, FH-sandeepkaur1 requested changes
Please check spellings mistakes

2022-01-24 04:23 UTC, kunalfleethawks commented on src/app/pages/manage/settings/veh-import/veh-import.component.ts
> +          this.toastr.success("Imported Successfully")
Instead of: Imported successfully.  
The file has been scheduled for processing and you will be notified via email once it is completed.

2022-01-24 05:12 UTC, PratikGanjareFleetHawks commented on src/app/pages/manage/settings/veh-import/veh-import.component.ts
> +         this.toastr.error("'Recored should be less than 200'")}
Done

2022-01-24 05:12 UTC, PratikGanjareFleetHawks commented on src/app/pages/manage/settings/veh-import/veh-import.component.ts
> +          this.toastr.success("Imported Successfully")
Done

2022-03-16 07:07 UTC, kunalfleethawks approved these changes

2022-03-16 07:08 UTC, merged