feat: multicompany
Fleet-Hawks-Inc/fh-cloud-app pull request #2553
Opened 2022-03-20 04:52 UTC by FH-sandeepkaur1

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-31 14:40 UTC, kunalfleethawks requested changes
Please have look at minor comments

2022-03-31 14:40 UTC, kunalfleethawks commented on src/app/entry/list-organizations/list-organizations.component.ts
> +    console.log('currentUser', this.currentUser)
remove console log

2022-03-31 14:40 UTC, kunalfleethawks commented on src/app/entry/list-organizations/list-organizations.component.ts
> +    localStorage.setItem('xfhCarrierId', data.carrierID);
we need to secure this as if someone tampers it - they can manipulate carriers.

2022-03-31 14:40 UTC, kunalfleethawks commented on src/app/pages/accounts/sales/sales-orders/add-sales-order/add-sales-order.component.ts
> +    // this.currentUser = (await Auth.currentSession()).getIdToken().payload;
Remove commented code

2022-03-31 14:40 UTC, kunalfleethawks commented on src/app/pages/dispatch/new-documents/my-documents/my-document-list.component.ts
> +    // this.currentUser = `${this.currentUser.firstName} ${this.currentUser.lastName}`;
remove all commented code

2022-04-01 23:19 UTC, FH-sandeepkaur1 commented on src/app/entry/list-organizations/list-organizations.component.ts
> +    localStorage.setItem('xfhCarrierId', data.carrierID);
Can you please the method for the same

2022-04-02 15:00 UTC, kunalfleethawks approved these changes

2022-04-02 15:00 UTC, merged