refactor: invetory updates to inventory
Fleet-Hawks-Inc/fh-cloud-app pull request #294
Opened 2020-12-12 15:34 UTC by gauravfleethawks

1) Input fields types updated in Inventory 2) warehouse modal added in inventory 3) delete added in inventory

BREAKING CHANGE: `extends` key in config file is now used for extending other config files

2020-12-14 10:54 UTC, kunalfleethawks requested changes
Please updated PR title which reflects to changes you have done.

2020-12-14 11:07 UTC, gauravfleethawks commented
> Please updated PR title which reflects to changes you have done.

done

2020-12-14 11:23 UTC, kunalfleethawks approved these changes

2020-12-14 11:39 UTC, kunalfleethawks approved these changes

2020-12-15 13:18 UTC, kunalfleethawks approved these changes
Looks good. Please get it approved from @amritfleethawks

2020-12-15 18:57 UTC, amritfleethawks approved these changes

2020-12-15 18:57 UTC, merged