fix: route module changes and documents pagination
Fleet-Hawks-Inc/fh-cloud-app pull request #296
Opened 2020-12-12 17:59 UTC by FH-sandeepkaur1

2020-12-14 13:37 UTC, kunalfleethawks requested changes
Hi @FH-sandeepkaur1 Please address the review comments.

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/new-documents/my-documents/my-document-list.component.ts
> +    //   this.serviceUrl = this.serviceUrl + '&searchValue=' + this.filterValues.searchValue + "&startDate=" + this.filterValues.startDate + "&endDate=" + this.filterValues.endDate + "&category=" + t
If commented code is not needed please remove them

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/permanent-routing/add-route/add-route.component.ts
> +  // fetchCountries() {
Please remove commented code if not needed

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/permanent-routing/add-route/add-route.component.ts
> +    console.log("this.routeData", this.routeData);
Remove console.log

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/permanent-routing/add-route/add-route.component.ts
> +    console.log('this.routeData.stops', this.routeData.stops);
please remove console.log

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/permanent-routing/edit-route/edit-route.component.ts
> +    console.log("dff", elem, label);
remove console.log

2020-12-14 13:37 UTC, kunalfleethawks commented on src/app/pages/dispatch/permanent-routing/edit-route/edit-route.component.ts
> +    console.log("labelResult", labelResult);
remove console.log

2020-12-15 06:29 UTC, kunalfleethawks commented
Hi @FH-sandeepkaur1 Can you update the PR title with the meaningful message as discussed yesterday

2020-12-16 00:38 UTC, kunalfleethawks approved these changes
Looks good.

2020-12-16 18:43 UTC, amritfleethawks approved these changes

2020-12-16 18:44 UTC, merged