enhancement:  address-Book implemented
Fleet-Hawks-Inc/fh-cloud-app pull request #298
Opened 2020-12-14 19:01 UTC by Daljit-fleetHawks

## Change Description

Customer/Broker/Vendor/Shipper/Consignee/Staff/FC-Companies/Carrier forms and list updated except address column.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-15 06:35 UTC, kunalfleethawks requested changes
Please do the requested changes

2020-12-15 06:35 UTC, kunalfleethawks commented on src/app/pages/fleet/drivers/driver-list/driver-list.component.ts
> +          console.log('driver', drivers);
remove console.logs

2020-12-15 06:35 UTC, kunalfleethawks commented on src/app/pages/fleet/geofence/add-geofence/add-geofence.component.ts
> +        console.log('result', result);
please remove console.logs

2020-12-15 06:35 UTC, kunalfleethawks commented on src/app/pages/fleet/maintenance/service-log/add-service/add-service.component.ts
> +      console.log("reminder", this.reminders);
please review console.logs

2020-12-15 06:35 UTC, kunalfleethawks commented on src/app/pages/fleet/maintenance/service-log/service-detail/service-detail.component.ts
>        });
please remove console.logs

2020-12-15 20:35 UTC, amritfleethawks approved these changes

2020-12-15 20:35 UTC, amritfleethawks commented on src/app/pages/fleet/maintenance/service-log/service-detail/service-detail.component.ts
> +        console.log('vehiclesObject', this.vehiclesObject);
please remove this..

2020-12-16 09:40 UTC, Daljit-fleetHawks reviewed
changes done

2020-12-16 11:20 UTC, kunalfleethawks approved these changes
Looks good.

2020-12-16 12:16 UTC, merged