refactor: driver validation, documents types changes and console code removed
Fleet-Hawks-Inc/fh-cloud-app pull request #303
Opened 2020-12-15 18:17 UTC by Daljit-fleetHawks

## Change Description

I have resolved validation issue on driver form and updated documents types in driver list. and I did removed console.log code from some components like driver, geofences, maintenance etc. Also resolved routing issue on header links.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-15 20:12 UTC, amritfleethawks commented on src/app/pages/fleet/drivers/driver-list/driver-list.component.ts
>            console.log('driver delete', err);
please remove console log

2020-12-15 20:12 UTC, amritfleethawks approved these changes

2020-12-15 20:12 UTC, amritfleethawks commented on src/app/pages/fleet/maintenance/service-log/service-detail/service-detail.component.ts
> +        console.log('vehiclesObject', this.vehiclesObject);
please remove console log

2020-12-15 20:12 UTC, amritfleethawks commented on src/app/pages/fleet/drivers/driver-list/driver-list.component.ts
>            console.log('driver delete', err);
please remove console log

2020-12-16 00:35 UTC, kunalfleethawks requested changes
@Daljit-fleetHawks please resolve the comments

2020-12-16 00:35 UTC, kunalfleethawks commented on src/app/pages/fleet/assets/asset-detail/asset-detail.component.ts
>          console.log('asset detail', err);
Remove console.logs

2020-12-16 00:36 UTC, kunalfleethawks approved these changes

2020-12-16 09:35 UTC, Daljit-fleetHawks reviewed
changes done

2020-12-16 11:17 UTC, merged