fix: vehicle and Inventory fixes
Fleet-Hawks-Inc/fh-cloud-app pull request #304
Opened 2020-12-16 15:11 UTC by gauravfleethawks

## Change Description

1) Map view page added in vehicles list
2) Fixes in the Detail page of vehicles
3) Fixes in Inventory

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-16 15:18 UTC, kunalfleethawks approved these changes
Looks Good. Approved Please ask @amritfleethawks to approve and merge

2020-12-17 12:01 UTC, amritfleethawks requested changes
gaurav please resolve conflicts...

2020-12-17 12:19 UTC, gauravfleethawks commented
> gaurav please resolve conflicts...

Done. Please proceed.

> gaurav please resolve conflicts...

Done..Please proceed.

2020-12-17 12:19 UTC, amritfleethawks approved these changes

2020-12-17 12:19 UTC, merged