feat: pagination added in assets-reminders-company documents
Fleet-Hawks-Inc/fh-cloud-app pull request #306
Opened 2020-12-16 18:20 UTC by FH-sandeepkaur1

## Change Description

Changes made in following modules for pagination
1. Documents in routing and dispatch
2. assets in fleet
3. reminders in fleet

Listing fixes in routing module of routing and dispatch

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist: (Check only applicable)

- [y ] My code follows the style guidelines of this project
- [y ] I have performed a self-review of my own code
- [y ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [y ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-16 20:01 UTC, amritfleethawks approved these changes

2020-12-17 08:02 UTC, kunalfleethawks requested changes
@FH-sandeepkaur1 Please remove commented code.

2020-12-17 08:02 UTC, kunalfleethawks commented on src/app/pages/fleet/assets/asset-list/asset-list.component.ts
>        //   setTimeout(() => {
Please remove the commented code.

2020-12-17 08:02 UTC, kunalfleethawks commented on src/app/pages/fleet/assets/asset-list/asset-list.component.ts
> +  //   this.reeferOptions = { // Reefer list options
Please remove the commented code.

2020-12-17 08:02 UTC, kunalfleethawks commented on src/app/pages/fleet/reminders/vehicle-renewals/vehicle-renew-list/vehicle-renew-list.component.ts
> +  //             reminderTasks: {
Please remove commented code.

2020-12-17 09:18 UTC, kunalfleethawks approved these changes

2020-12-17 09:18 UTC, merged