fix: validations in manifests ace/aci
Fleet-Hawks-Inc/fh-cloud-app pull request #378
Opened 2021-01-18 16:09 UTC by Hardeep8587

## Change Description
validations in ace/aci
extra comonents deleted 
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-01-18 16:17 UTC, Hardeep8587 commented
@kunalfleethawks @amritfleethawks Please review and merge

2021-01-20 15:26 UTC, kunalfleethawks approved these changes

2021-01-20 15:26 UTC, kunalfleethawks commented on src/app/pages/dispatch/cross-border/aci-documents/new-aci-manifest/new-aci-manifest.component.ts
> +        this.location.back(); // <-- go back to previous location
Manifest Updated Successfully (add a period after message)

2021-01-21 12:25 UTC, amritfleethawks approved these changes

2021-01-21 13:05 UTC, amritfleethawks requested changes

2021-01-21 13:05 UTC, amritfleethawks commented on src/app/pages/dispatch/new-documents/company-documents/company-documents.component.ts
> +  documentData = {=
hardeep please remove '='

2021-01-21 13:12 UTC, Hardeep8587 commented on src/app/pages/dispatch/new-documents/company-documents/company-documents.component.ts
> +  documentData = {=
done !

2021-01-21 14:35 UTC, amritfleethawks approved these changes

2021-01-21 14:35 UTC, merged