fix: trip status changes in planner and trips
Fleet-Hawks-Inc/fh-cloud-app pull request #475
Opened 2021-02-17 12:28 UTC by FH-sandeepkaur1

## Change Description

trip status changes in planner and trips

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-18 04:55 UTC, kunalfleethawks requested changes

2021-02-18 04:55 UTC, kunalfleethawks commented on src/app/pages/dispatch/dispatch.module.ts
> +  // toModel(date: NgbDateStruct | null): string | null {
remove commented code if not required.

2021-02-18 04:55 UTC, kunalfleethawks commented on src/app/pages/dispatch/home/dispatch-overview/dispatch-overview.component.ts
> +            // for (let j = 0; j < element.tripPlanning.length; j++) {
Remove commented code if not required.

2021-02-18 04:55 UTC, kunalfleethawks commented on src/app/pages/dispatch/planner/calendar-view/calendar-view.component.ts
>            this.toastr.error('Trip plan for selected trip is empty. Please create one to assign');
Please update the sentence to:
Trip plan for selected trip is empty. Please create one to assign
TO 
The trip plan for the selected trip is empty. Please create one to assign.

2021-02-18 04:55 UTC, kunalfleethawks commented on src/app/pages/dispatch/trips/trip-detail/trip-detail.component.ts
> +            //   countryID: element.location.countryID,
remove this code if not required.

2021-02-19 04:00 UTC, FH-sandeepkaur1 reviewed
Commented code is removed. Please review

2021-02-19 12:00 UTC, kunalfleethawks approved these changes

2021-02-20 04:41 UTC, merged