enhancement:  manifest validations
Fleet-Hawks-Inc/fh-cloud-app pull request #479
Opened 2021-02-18 11:57 UTC by Hardeep8587

## Change Description

Shipper/consignee pop ups ,
 city state country pop ups,
ACE date,
main driver/co driver

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-18 11:58 UTC, Hardeep8587 commented
@kunalfleethawks Please review and merge! thanku !

2021-02-18 12:19 UTC, kunalfleethawks commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.ts
> +  // fetchShippers(){
If this code is not required, please remove

2021-02-18 12:20 UTC, kunalfleethawks commented on src/app/pages/dispatch/cross-border/aci-documents/new-aci-manifest/new-aci-manifest.component.ts
> +  // getDocStates(){
If this code is not required please remove it.

2021-02-18 12:20 UTC, kunalfleethawks commented on src/app/pages/dispatch/dispatch.module.ts
> +  // fromModel(value: string | null): NgbDateStruct | null {
Please remove this

2021-02-18 12:21 UTC, kunalfleethawks requested changes
Please address the review comments

2021-02-18 12:35 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/ace-documents/new-ace-manifest/new-ace-manifest.component.ts
> +  // fetchShippers(){
please hold for a day, after integration will remove..

2021-02-18 12:35 UTC, Hardeep8587 commented on src/app/pages/dispatch/cross-border/aci-documents/new-aci-manifest/new-aci-manifest.component.ts
> +  // getDocStates(){
please hold for a day, after integration will remove..

2021-02-19 06:50 UTC, Hardeep8587 commented
@kunalfleethawks please merge! I will remove all commented code, as soon as I get response...just keeping as security

2021-02-19 06:50 UTC, closed without merging