fix: maps to truck specific
Fleet-Hawks-Inc/fh-cloud-app pull request #706
Opened 2021-03-19 19:43 UTC by AmitojSingh1

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-20 04:06 UTC, kunalfleethawks requested changes

2021-03-20 04:06 UTC, kunalfleethawks commented on src/app/pages/dispatch/trips/add-trip/add-trip.component.ts
> +            console.log("No vehicle is specified");
Do not put console logs as this would be available on Chrome console

2021-03-20 04:06 UTC, kunalfleethawks commented on src/app/pages/dispatch/trips/add-trip/add-trip.component.ts
> +        console.log("this.trips",this.trips);
Please remove this as well

2021-03-22 04:12 UTC, kunalfleethawks commented on src/app/pages/dispatch/trips/add-trip/add-trip.component.ts
> +            console.log(this.optionalSpec)
Please remove console logs

2021-03-23 18:07 UTC, AmitojSingh1 commented on src/app/pages/dispatch/trips/add-trip/add-trip.component.ts
> +        console.log("this.trips",this.trips);
already removed

2021-03-23 18:09 UTC, AmitojSingh1 commented on src/app/pages/dispatch/trips/add-trip/add-trip.component.ts
> +            console.log("No vehicle is specified");
Fixed

2021-03-24 04:32 UTC, kunalfleethawks approved these changes

2021-03-24 04:32 UTC, merged