fix: log and reminder changes
Fleet-Hawks-Inc/fh-cloud-app pull request #824
Opened 2021-03-25 12:41 UTC by Daljit-fleetHawks

## Change Description

update odometer/completion date in reminder and log changes

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-25 12:50 UTC, kunalfleethawks requested changes

2021-03-25 12:50 UTC, kunalfleethawks commented on src/app/pages/fleet/geofence/geofence-list/geofence-list.component.ts
>      this.spinner.show();
Can you remove the spinner. We are not showing spinner.

2021-03-25 12:50 UTC, kunalfleethawks commented on src/app/pages/fleet/maintenance/service-log/service-list/service-list.component.ts
>      this.spinner.show();
Please remove spinner

2021-03-26 04:18 UTC, kunalfleethawks approved these changes

2021-03-26 04:19 UTC, kunalfleethawks commented
please resolve conflicts

2021-03-26 04:21 UTC, Daljit-fleetHawks commented
> please resolve conflicts

Done

2021-03-26 04:29 UTC, merged