feat: e2e cypress testing
Fleet-Hawks-Inc/fh-cloud-app pull request #886
Opened 2021-04-05 11:52 UTC by nameetjambla

## Change Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: (Check only applicable)

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-04-05 13:41 UTC, kunalfleethawks requested changes
Please address the comments

2021-04-05 13:41 UTC, kunalfleethawks commented on cypress.json
> +    "viewportWidth":1920
Keep this as it is  and use it accordingly in all the test files
 "testerUserName":"e2etestcarrier",
     "testerPassword":"FleetHawks@1302"

2021-04-05 13:41 UTC, kunalfleethawks commented on cypress/integration/add-asset.js
> +    cy.wait(5000);
cy.get(':nth-child(1) > .input-group > .form-control').type(Cypress.config('testerUserName'));
cy.get(':nth-child(1) > .input-group > .form-control').type(Cypress.config('testerPassword'));

2021-04-05 13:41 UTC, kunalfleethawks commented on cypress/integration/add-driver.js
> +        cy.visit('http://cloudapp.fleethawks.com/#/Login/');
cy.visit('#/Login/');
Change all the cy.visit() with actual pages.

2021-04-05 13:41 UTC, kunalfleethawks commented on cypress/integration/delete-asset.js
> +  cy.visit('http://cloudapp.fleethawks.com/#/Login/');
Change to relative url

2021-04-05 13:41 UTC, kunalfleethawks commented on cypress/integration/loginPassTest.js
> +  cy.visit('http://cloudapp.fleethawks.com/#/Login/');
Change this to relative url

2021-04-06 05:58 UTC, nameetjambla commented on cypress.json
> +    "viewportWidth":1920
Done

2021-04-06 05:58 UTC, nameetjambla commented on cypress/integration/add-asset.js
> +    cy.wait(5000);
done

2021-04-06 05:58 UTC, nameetjambla commented on cypress/integration/add-driver.js
> +        cy.visit('http://cloudapp.fleethawks.com/#/Login/');
done

2021-04-06 05:58 UTC, nameetjambla commented on cypress/integration/delete-asset.js
> +  cy.visit('http://cloudapp.fleethawks.com/#/Login/');
done

2021-04-06 05:58 UTC, nameetjambla commented on cypress/integration/loginPassTest.js
> +  cy.visit('http://cloudapp.fleethawks.com/#/Login/');
done

2021-04-07 05:24 UTC, kunalfleethawks requested changes

2021-04-07 05:24 UTC, kunalfleethawks commented on cypress/fixtures/example.json
> -  "name": "Using fixtures to represent data",
Delete this file

2021-04-07 05:24 UTC, kunalfleethawks commented on cypress/fixtures/method.txt
> +import { browser, by, element, ElementFinder, ExpectedConditions, WebElementPromise } from 'protractor';
delete this file

2021-04-07 05:24 UTC, kunalfleethawks commented on cypress/integration/Login Test/loginTests.js
> +    cy.get(':nth-child(1) > .input-group > .form-control').clear();
describe (Login Tests):
it ( should allow user to login when valid credentails are provided
it( should fail with errormessage when invalid credentials are provided)
it(should give validation error message when either username or password is not provided

2021-04-07 05:24 UTC, kunalfleethawks commented on cypress/integration/Login Test/loginTests.js
> +it('login and then go to Map Dashdashboard and then add asset and then delete asset', function () {
Move this to New File
describe (“Asset tests”)
it should allow user to add asset
it should list the assed which was added (verify the added asset is listed by name/other properties)
it should allow user to search by asset name and other properties
it should allow user to delete asset
it should not be listed (verify assed which was added is not listed)
it should give validation error message when required fields are not provided

2021-04-07 05:24 UTC, kunalfleethawks commented on package.json
> +    "@angular/cli": "^11.2.7",
revert this change

2021-04-07 05:34 UTC, kunalfleethawks requested changes
@nameetjambla please address the review comments

2021-04-07 05:34 UTC, kunalfleethawks commented on package.json
> +    "karma": "^6.3.2",
revert this

2021-04-07 05:34 UTC, kunalfleethawks commented on package.json
> +    "protractor": "^5.4.4",
revert

2021-04-07 05:34 UTC, kunalfleethawks commented on report.20210405.141638.6720.0.001.json
> +
delete this file

2021-04-07 06:55 UTC, nameetjambla commented on cypress/fixtures/example.json
> -  "name": "Using fixtures to represent data",
Issue Solved

2021-04-07 06:57 UTC, nameetjambla commented on package.json
> +    "@angular/cli": "^11.2.7",
Issue Solved

2021-04-07 06:57 UTC, nameetjambla commented on package.json
> +    "protractor": "^5.4.4",
Issue Solved

2021-04-07 06:58 UTC, nameetjambla commented on report.20210405.141638.6720.0.001.json
> +
Issue Solved

2021-04-07 06:59 UTC, nameetjambla commented on package.json
> +    "karma": "^6.3.2",
Issue Solved

2021-04-07 06:59 UTC, nameetjambla commented on cypress/fixtures/method.txt
> +import { browser, by, element, ElementFinder, ExpectedConditions, WebElementPromise } from 'protractor';
Issue Solved

2021-04-09 13:02 UTC, kunalfleethawks approved these changes

2021-04-09 13:03 UTC, merged